// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/sentence-gen.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SentenceGen_HelloWorld_FullMethodName = "/sentencegen.SentenceGen/HelloWorld"
)

// SentenceGenClient is the client API for SentenceGen service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SentenceGenClient interface {
	HelloWorld(ctx context.Context, in *HelloWorldRequest, opts ...grpc.CallOption) (*HelloWorldResponse, error)
}

type sentenceGenClient struct {
	cc grpc.ClientConnInterface
}

func NewSentenceGenClient(cc grpc.ClientConnInterface) SentenceGenClient {
	return &sentenceGenClient{cc}
}

func (c *sentenceGenClient) HelloWorld(ctx context.Context, in *HelloWorldRequest, opts ...grpc.CallOption) (*HelloWorldResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HelloWorldResponse)
	err := c.cc.Invoke(ctx, SentenceGen_HelloWorld_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SentenceGenServer is the server API for SentenceGen service.
// All implementations must embed UnimplementedSentenceGenServer
// for forward compatibility.
type SentenceGenServer interface {
	HelloWorld(context.Context, *HelloWorldRequest) (*HelloWorldResponse, error)
	mustEmbedUnimplementedSentenceGenServer()
}

// UnimplementedSentenceGenServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSentenceGenServer struct{}

func (UnimplementedSentenceGenServer) HelloWorld(context.Context, *HelloWorldRequest) (*HelloWorldResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HelloWorld not implemented")
}
func (UnimplementedSentenceGenServer) mustEmbedUnimplementedSentenceGenServer() {}
func (UnimplementedSentenceGenServer) testEmbeddedByValue()                     {}

// UnsafeSentenceGenServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SentenceGenServer will
// result in compilation errors.
type UnsafeSentenceGenServer interface {
	mustEmbedUnimplementedSentenceGenServer()
}

func RegisterSentenceGenServer(s grpc.ServiceRegistrar, srv SentenceGenServer) {
	// If the following call pancis, it indicates UnimplementedSentenceGenServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SentenceGen_ServiceDesc, srv)
}

func _SentenceGen_HelloWorld_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloWorldRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SentenceGenServer).HelloWorld(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SentenceGen_HelloWorld_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SentenceGenServer).HelloWorld(ctx, req.(*HelloWorldRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SentenceGen_ServiceDesc is the grpc.ServiceDesc for SentenceGen service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SentenceGen_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sentencegen.SentenceGen",
	HandlerType: (*SentenceGenServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HelloWorld",
			Handler:    _SentenceGen_HelloWorld_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/sentence-gen.proto",
}
