// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: proto/sentence-gen.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Audio struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Audio) Reset() {
	*x = Audio{}
	mi := &file_proto_sentence_gen_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Audio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Audio) ProtoMessage() {}

func (x *Audio) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sentence_gen_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Audio.ProtoReflect.Descriptor instead.
func (*Audio) Descriptor() ([]byte, []int) {
	return file_proto_sentence_gen_proto_rawDescGZIP(), []int{0}
}

func (x *Audio) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type GenerateSentenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromLanguage  string                 `protobuf:"bytes,1,opt,name=from_language,json=fromLanguage,proto3" json:"from_language,omitempty"`
	ToLanguage    string                 `protobuf:"bytes,2,opt,name=to_language,json=toLanguage,proto3" json:"to_language,omitempty"`
	Word          string                 `protobuf:"bytes,3,opt,name=word,proto3" json:"word,omitempty"`
	Translation   string                 `protobuf:"bytes,4,opt,name=translation,proto3" json:"translation,omitempty"`
	IncludeAudio  bool                   `protobuf:"varint,5,opt,name=include_audio,json=includeAudio,proto3" json:"include_audio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateSentenceRequest) Reset() {
	*x = GenerateSentenceRequest{}
	mi := &file_proto_sentence_gen_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateSentenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateSentenceRequest) ProtoMessage() {}

func (x *GenerateSentenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sentence_gen_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateSentenceRequest.ProtoReflect.Descriptor instead.
func (*GenerateSentenceRequest) Descriptor() ([]byte, []int) {
	return file_proto_sentence_gen_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateSentenceRequest) GetFromLanguage() string {
	if x != nil {
		return x.FromLanguage
	}
	return ""
}

func (x *GenerateSentenceRequest) GetToLanguage() string {
	if x != nil {
		return x.ToLanguage
	}
	return ""
}

func (x *GenerateSentenceRequest) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

func (x *GenerateSentenceRequest) GetTranslation() string {
	if x != nil {
		return x.Translation
	}
	return ""
}

func (x *GenerateSentenceRequest) GetIncludeAudio() bool {
	if x != nil {
		return x.IncludeAudio
	}
	return false
}

type GenerateSentenceResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	OriginalSentence   string                 `protobuf:"bytes,1,opt,name=original_sentence,json=originalSentence,proto3" json:"original_sentence,omitempty"`
	TranslatedSentence string                 `protobuf:"bytes,2,opt,name=translated_sentence,json=translatedSentence,proto3" json:"translated_sentence,omitempty"`
	Audio              *Audio                 `protobuf:"bytes,3,opt,name=audio,proto3" json:"audio,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GenerateSentenceResponse) Reset() {
	*x = GenerateSentenceResponse{}
	mi := &file_proto_sentence_gen_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateSentenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateSentenceResponse) ProtoMessage() {}

func (x *GenerateSentenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sentence_gen_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateSentenceResponse.ProtoReflect.Descriptor instead.
func (*GenerateSentenceResponse) Descriptor() ([]byte, []int) {
	return file_proto_sentence_gen_proto_rawDescGZIP(), []int{2}
}

func (x *GenerateSentenceResponse) GetOriginalSentence() string {
	if x != nil {
		return x.OriginalSentence
	}
	return ""
}

func (x *GenerateSentenceResponse) GetTranslatedSentence() string {
	if x != nil {
		return x.TranslatedSentence
	}
	return ""
}

func (x *GenerateSentenceResponse) GetAudio() *Audio {
	if x != nil {
		return x.Audio
	}
	return nil
}

type GenerateDefinitionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Language       string                 `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	Word           string                 `protobuf:"bytes,2,opt,name=word,proto3" json:"word,omitempty"`
	DefinitionHint string                 `protobuf:"bytes,3,opt,name=definition_hint,json=definitionHint,proto3" json:"definition_hint,omitempty"`
	IncludeAudio   bool                   `protobuf:"varint,4,opt,name=include_audio,json=includeAudio,proto3" json:"include_audio,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GenerateDefinitionRequest) Reset() {
	*x = GenerateDefinitionRequest{}
	mi := &file_proto_sentence_gen_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateDefinitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateDefinitionRequest) ProtoMessage() {}

func (x *GenerateDefinitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sentence_gen_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateDefinitionRequest.ProtoReflect.Descriptor instead.
func (*GenerateDefinitionRequest) Descriptor() ([]byte, []int) {
	return file_proto_sentence_gen_proto_rawDescGZIP(), []int{3}
}

func (x *GenerateDefinitionRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *GenerateDefinitionRequest) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

func (x *GenerateDefinitionRequest) GetDefinitionHint() string {
	if x != nil {
		return x.DefinitionHint
	}
	return ""
}

func (x *GenerateDefinitionRequest) GetIncludeAudio() bool {
	if x != nil {
		return x.IncludeAudio
	}
	return false
}

type GenerateDefinitionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Word          string                 `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	Definition    string                 `protobuf:"bytes,2,opt,name=definition,proto3" json:"definition,omitempty"`
	Audio         *Audio                 `protobuf:"bytes,3,opt,name=audio,proto3" json:"audio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateDefinitionResponse) Reset() {
	*x = GenerateDefinitionResponse{}
	mi := &file_proto_sentence_gen_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateDefinitionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateDefinitionResponse) ProtoMessage() {}

func (x *GenerateDefinitionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sentence_gen_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateDefinitionResponse.ProtoReflect.Descriptor instead.
func (*GenerateDefinitionResponse) Descriptor() ([]byte, []int) {
	return file_proto_sentence_gen_proto_rawDescGZIP(), []int{4}
}

func (x *GenerateDefinitionResponse) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

func (x *GenerateDefinitionResponse) GetDefinition() string {
	if x != nil {
		return x.Definition
	}
	return ""
}

func (x *GenerateDefinitionResponse) GetAudio() *Audio {
	if x != nil {
		return x.Audio
	}
	return nil
}

type TranslateWordRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FromLanguage    string                 `protobuf:"bytes,1,opt,name=from_language,json=fromLanguage,proto3" json:"from_language,omitempty"`
	ToLanguage      string                 `protobuf:"bytes,2,opt,name=to_language,json=toLanguage,proto3" json:"to_language,omitempty"`
	Word            string                 `protobuf:"bytes,3,opt,name=word,proto3" json:"word,omitempty"`
	TranslationHint string                 `protobuf:"bytes,4,opt,name=translation_hint,json=translationHint,proto3" json:"translation_hint,omitempty"`
	IncludeAudio    bool                   `protobuf:"varint,5,opt,name=include_audio,json=includeAudio,proto3" json:"include_audio,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TranslateWordRequest) Reset() {
	*x = TranslateWordRequest{}
	mi := &file_proto_sentence_gen_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranslateWordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslateWordRequest) ProtoMessage() {}

func (x *TranslateWordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sentence_gen_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslateWordRequest.ProtoReflect.Descriptor instead.
func (*TranslateWordRequest) Descriptor() ([]byte, []int) {
	return file_proto_sentence_gen_proto_rawDescGZIP(), []int{5}
}

func (x *TranslateWordRequest) GetFromLanguage() string {
	if x != nil {
		return x.FromLanguage
	}
	return ""
}

func (x *TranslateWordRequest) GetToLanguage() string {
	if x != nil {
		return x.ToLanguage
	}
	return ""
}

func (x *TranslateWordRequest) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

func (x *TranslateWordRequest) GetTranslationHint() string {
	if x != nil {
		return x.TranslationHint
	}
	return ""
}

func (x *TranslateWordRequest) GetIncludeAudio() bool {
	if x != nil {
		return x.IncludeAudio
	}
	return false
}

type TranslateWordResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OriginalWord   string                 `protobuf:"bytes,1,opt,name=original_word,json=originalWord,proto3" json:"original_word,omitempty"`
	TranslatedWord string                 `protobuf:"bytes,2,opt,name=translated_word,json=translatedWord,proto3" json:"translated_word,omitempty"`
	Audio          *Audio                 `protobuf:"bytes,3,opt,name=audio,proto3" json:"audio,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TranslateWordResponse) Reset() {
	*x = TranslateWordResponse{}
	mi := &file_proto_sentence_gen_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranslateWordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslateWordResponse) ProtoMessage() {}

func (x *TranslateWordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sentence_gen_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslateWordResponse.ProtoReflect.Descriptor instead.
func (*TranslateWordResponse) Descriptor() ([]byte, []int) {
	return file_proto_sentence_gen_proto_rawDescGZIP(), []int{6}
}

func (x *TranslateWordResponse) GetOriginalWord() string {
	if x != nil {
		return x.OriginalWord
	}
	return ""
}

func (x *TranslateWordResponse) GetTranslatedWord() string {
	if x != nil {
		return x.TranslatedWord
	}
	return ""
}

func (x *TranslateWordResponse) GetAudio() *Audio {
	if x != nil {
		return x.Audio
	}
	return nil
}

var File_proto_sentence_gen_proto protoreflect.FileDescriptor

const file_proto_sentence_gen_proto_rawDesc = "" +
	"\n" +
	"\x18proto/sentence-gen.proto\x12\vsentencegen\"\x1b\n" +
	"\x05Audio\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\xba\x01\n" +
	"\x17GenerateSentenceRequest\x12#\n" +
	"\rfrom_language\x18\x01 \x01(\tR\ffromLanguage\x12\x1f\n" +
	"\vto_language\x18\x02 \x01(\tR\n" +
	"toLanguage\x12\x12\n" +
	"\x04word\x18\x03 \x01(\tR\x04word\x12 \n" +
	"\vtranslation\x18\x04 \x01(\tR\vtranslation\x12#\n" +
	"\rinclude_audio\x18\x05 \x01(\bR\fincludeAudio\"\xa2\x01\n" +
	"\x18GenerateSentenceResponse\x12+\n" +
	"\x11original_sentence\x18\x01 \x01(\tR\x10originalSentence\x12/\n" +
	"\x13translated_sentence\x18\x02 \x01(\tR\x12translatedSentence\x12(\n" +
	"\x05audio\x18\x03 \x01(\v2\x12.sentencegen.AudioR\x05audio\"\x99\x01\n" +
	"\x19GenerateDefinitionRequest\x12\x1a\n" +
	"\blanguage\x18\x01 \x01(\tR\blanguage\x12\x12\n" +
	"\x04word\x18\x02 \x01(\tR\x04word\x12'\n" +
	"\x0fdefinition_hint\x18\x03 \x01(\tR\x0edefinitionHint\x12#\n" +
	"\rinclude_audio\x18\x04 \x01(\bR\fincludeAudio\"z\n" +
	"\x1aGenerateDefinitionResponse\x12\x12\n" +
	"\x04word\x18\x01 \x01(\tR\x04word\x12\x1e\n" +
	"\n" +
	"definition\x18\x02 \x01(\tR\n" +
	"definition\x12(\n" +
	"\x05audio\x18\x03 \x01(\v2\x12.sentencegen.AudioR\x05audio\"\xc0\x01\n" +
	"\x14TranslateWordRequest\x12#\n" +
	"\rfrom_language\x18\x01 \x01(\tR\ffromLanguage\x12\x1f\n" +
	"\vto_language\x18\x02 \x01(\tR\n" +
	"toLanguage\x12\x12\n" +
	"\x04word\x18\x03 \x01(\tR\x04word\x12)\n" +
	"\x10translation_hint\x18\x04 \x01(\tR\x0ftranslationHint\x12#\n" +
	"\rinclude_audio\x18\x05 \x01(\bR\fincludeAudio\"\x8f\x01\n" +
	"\x15TranslateWordResponse\x12#\n" +
	"\roriginal_word\x18\x01 \x01(\tR\foriginalWord\x12'\n" +
	"\x0ftranslated_word\x18\x02 \x01(\tR\x0etranslatedWord\x12(\n" +
	"\x05audio\x18\x03 \x01(\v2\x12.sentencegen.AudioR\x05audio2\xad\x02\n" +
	"\vSentenceGen\x12_\n" +
	"\x10GenerateSentence\x12$.sentencegen.GenerateSentenceRequest\x1a%.sentencegen.GenerateSentenceResponse\x12V\n" +
	"\rTranslateWord\x12!.sentencegen.TranslateWordRequest\x1a\".sentencegen.TranslateWordResponse\x12e\n" +
	"\x12GenerateDefinition\x12&.sentencegen.GenerateDefinitionRequest\x1a'.sentencegen.GenerateDefinitionResponseB\x0eZ\fclient/protob\x06proto3"

var (
	file_proto_sentence_gen_proto_rawDescOnce sync.Once
	file_proto_sentence_gen_proto_rawDescData []byte
)

func file_proto_sentence_gen_proto_rawDescGZIP() []byte {
	file_proto_sentence_gen_proto_rawDescOnce.Do(func() {
		file_proto_sentence_gen_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sentence_gen_proto_rawDesc), len(file_proto_sentence_gen_proto_rawDesc)))
	})
	return file_proto_sentence_gen_proto_rawDescData
}

var file_proto_sentence_gen_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_sentence_gen_proto_goTypes = []any{
	(*Audio)(nil),                      // 0: sentencegen.Audio
	(*GenerateSentenceRequest)(nil),    // 1: sentencegen.GenerateSentenceRequest
	(*GenerateSentenceResponse)(nil),   // 2: sentencegen.GenerateSentenceResponse
	(*GenerateDefinitionRequest)(nil),  // 3: sentencegen.GenerateDefinitionRequest
	(*GenerateDefinitionResponse)(nil), // 4: sentencegen.GenerateDefinitionResponse
	(*TranslateWordRequest)(nil),       // 5: sentencegen.TranslateWordRequest
	(*TranslateWordResponse)(nil),      // 6: sentencegen.TranslateWordResponse
}
var file_proto_sentence_gen_proto_depIdxs = []int32{
	0, // 0: sentencegen.GenerateSentenceResponse.audio:type_name -> sentencegen.Audio
	0, // 1: sentencegen.GenerateDefinitionResponse.audio:type_name -> sentencegen.Audio
	0, // 2: sentencegen.TranslateWordResponse.audio:type_name -> sentencegen.Audio
	1, // 3: sentencegen.SentenceGen.GenerateSentence:input_type -> sentencegen.GenerateSentenceRequest
	5, // 4: sentencegen.SentenceGen.TranslateWord:input_type -> sentencegen.TranslateWordRequest
	3, // 5: sentencegen.SentenceGen.GenerateDefinition:input_type -> sentencegen.GenerateDefinitionRequest
	2, // 6: sentencegen.SentenceGen.GenerateSentence:output_type -> sentencegen.GenerateSentenceResponse
	6, // 7: sentencegen.SentenceGen.TranslateWord:output_type -> sentencegen.TranslateWordResponse
	4, // 8: sentencegen.SentenceGen.GenerateDefinition:output_type -> sentencegen.GenerateDefinitionResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_sentence_gen_proto_init() }
func file_proto_sentence_gen_proto_init() {
	if File_proto_sentence_gen_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sentence_gen_proto_rawDesc), len(file_proto_sentence_gen_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_sentence_gen_proto_goTypes,
		DependencyIndexes: file_proto_sentence_gen_proto_depIdxs,
		MessageInfos:      file_proto_sentence_gen_proto_msgTypes,
	}.Build()
	File_proto_sentence_gen_proto = out.File
	file_proto_sentence_gen_proto_goTypes = nil
	file_proto_sentence_gen_proto_depIdxs = nil
}
