// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/sentence-gen.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HelloWorldRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloWorldRequest) Reset() {
	*x = HelloWorldRequest{}
	mi := &file_proto_sentence_gen_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloWorldRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloWorldRequest) ProtoMessage() {}

func (x *HelloWorldRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sentence_gen_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloWorldRequest.ProtoReflect.Descriptor instead.
func (*HelloWorldRequest) Descriptor() ([]byte, []int) {
	return file_proto_sentence_gen_proto_rawDescGZIP(), []int{0}
}

type HelloWorldResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloWorldResponse) Reset() {
	*x = HelloWorldResponse{}
	mi := &file_proto_sentence_gen_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloWorldResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloWorldResponse) ProtoMessage() {}

func (x *HelloWorldResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sentence_gen_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloWorldResponse.ProtoReflect.Descriptor instead.
func (*HelloWorldResponse) Descriptor() ([]byte, []int) {
	return file_proto_sentence_gen_proto_rawDescGZIP(), []int{1}
}

func (x *HelloWorldResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_sentence_gen_proto protoreflect.FileDescriptor

const file_proto_sentence_gen_proto_rawDesc = "" +
	"\n" +
	"\x18proto/sentence-gen.proto\x12\vsentencegen\"\x13\n" +
	"\x11HelloWorldRequest\".\n" +
	"\x12HelloWorldResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\\\n" +
	"\vSentenceGen\x12M\n" +
	"\n" +
	"HelloWorld\x12\x1e.sentencegen.HelloWorldRequest\x1a\x1f.sentencegen.HelloWorldResponseB3Z1github.com/dafraer/sentence-gen-grpc-server/protob\x06proto3"

var (
	file_proto_sentence_gen_proto_rawDescOnce sync.Once
	file_proto_sentence_gen_proto_rawDescData []byte
)

func file_proto_sentence_gen_proto_rawDescGZIP() []byte {
	file_proto_sentence_gen_proto_rawDescOnce.Do(func() {
		file_proto_sentence_gen_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sentence_gen_proto_rawDesc), len(file_proto_sentence_gen_proto_rawDesc)))
	})
	return file_proto_sentence_gen_proto_rawDescData
}

var file_proto_sentence_gen_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_sentence_gen_proto_goTypes = []any{
	(*HelloWorldRequest)(nil),  // 0: sentencegen.HelloWorldRequest
	(*HelloWorldResponse)(nil), // 1: sentencegen.HelloWorldResponse
}
var file_proto_sentence_gen_proto_depIdxs = []int32{
	0, // 0: sentencegen.SentenceGen.HelloWorld:input_type -> sentencegen.HelloWorldRequest
	1, // 1: sentencegen.SentenceGen.HelloWorld:output_type -> sentencegen.HelloWorldResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_sentence_gen_proto_init() }
func file_proto_sentence_gen_proto_init() {
	if File_proto_sentence_gen_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sentence_gen_proto_rawDesc), len(file_proto_sentence_gen_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_sentence_gen_proto_goTypes,
		DependencyIndexes: file_proto_sentence_gen_proto_depIdxs,
		MessageInfos:      file_proto_sentence_gen_proto_msgTypes,
	}.Build()
	File_proto_sentence_gen_proto = out.File
	file_proto_sentence_gen_proto_goTypes = nil
	file_proto_sentence_gen_proto_depIdxs = nil
}
