// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/sentence-gen.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SentenceGen_GenerateSentence_FullMethodName   = "/sentencegen.SentenceGen/GenerateSentence"
	SentenceGen_Translate_FullMethodName          = "/sentencegen.SentenceGen/Translate"
	SentenceGen_GenerateDefinition_FullMethodName = "/sentencegen.SentenceGen/GenerateDefinition"
)

// SentenceGenClient is the client API for SentenceGen service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SentenceGenClient interface {
	GenerateSentence(ctx context.Context, in *GenerateSentenceRequest, opts ...grpc.CallOption) (*GenerateSentenceResponse, error)
	Translate(ctx context.Context, in *TranslateRequest, opts ...grpc.CallOption) (*TranslateResponse, error)
	GenerateDefinition(ctx context.Context, in *GenerateDefinitionRequest, opts ...grpc.CallOption) (*GenerateDefinitionResponse, error)
}

type sentenceGenClient struct {
	cc grpc.ClientConnInterface
}

func NewSentenceGenClient(cc grpc.ClientConnInterface) SentenceGenClient {
	return &sentenceGenClient{cc}
}

func (c *sentenceGenClient) GenerateSentence(ctx context.Context, in *GenerateSentenceRequest, opts ...grpc.CallOption) (*GenerateSentenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateSentenceResponse)
	err := c.cc.Invoke(ctx, SentenceGen_GenerateSentence_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sentenceGenClient) Translate(ctx context.Context, in *TranslateRequest, opts ...grpc.CallOption) (*TranslateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TranslateResponse)
	err := c.cc.Invoke(ctx, SentenceGen_Translate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sentenceGenClient) GenerateDefinition(ctx context.Context, in *GenerateDefinitionRequest, opts ...grpc.CallOption) (*GenerateDefinitionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateDefinitionResponse)
	err := c.cc.Invoke(ctx, SentenceGen_GenerateDefinition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SentenceGenServer is the server API for SentenceGen service.
// All implementations must embed UnimplementedSentenceGenServer
// for forward compatibility.
type SentenceGenServer interface {
	GenerateSentence(context.Context, *GenerateSentenceRequest) (*GenerateSentenceResponse, error)
	Translate(context.Context, *TranslateRequest) (*TranslateResponse, error)
	GenerateDefinition(context.Context, *GenerateDefinitionRequest) (*GenerateDefinitionResponse, error)
	mustEmbedUnimplementedSentenceGenServer()
}

// UnimplementedSentenceGenServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSentenceGenServer struct{}

func (UnimplementedSentenceGenServer) GenerateSentence(context.Context, *GenerateSentenceRequest) (*GenerateSentenceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateSentence not implemented")
}
func (UnimplementedSentenceGenServer) Translate(context.Context, *TranslateRequest) (*TranslateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Translate not implemented")
}
func (UnimplementedSentenceGenServer) GenerateDefinition(context.Context, *GenerateDefinitionRequest) (*GenerateDefinitionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateDefinition not implemented")
}
func (UnimplementedSentenceGenServer) mustEmbedUnimplementedSentenceGenServer() {}
func (UnimplementedSentenceGenServer) testEmbeddedByValue()                     {}

// UnsafeSentenceGenServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SentenceGenServer will
// result in compilation errors.
type UnsafeSentenceGenServer interface {
	mustEmbedUnimplementedSentenceGenServer()
}

func RegisterSentenceGenServer(s grpc.ServiceRegistrar, srv SentenceGenServer) {
	// If the following call pancis, it indicates UnimplementedSentenceGenServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SentenceGen_ServiceDesc, srv)
}

func _SentenceGen_GenerateSentence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateSentenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SentenceGenServer).GenerateSentence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SentenceGen_GenerateSentence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SentenceGenServer).GenerateSentence(ctx, req.(*GenerateSentenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SentenceGen_Translate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TranslateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SentenceGenServer).Translate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SentenceGen_Translate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SentenceGenServer).Translate(ctx, req.(*TranslateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SentenceGen_GenerateDefinition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateDefinitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SentenceGenServer).GenerateDefinition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SentenceGen_GenerateDefinition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SentenceGenServer).GenerateDefinition(ctx, req.(*GenerateDefinitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SentenceGen_ServiceDesc is the grpc.ServiceDesc for SentenceGen service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SentenceGen_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sentencegen.SentenceGen",
	HandlerType: (*SentenceGenServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateSentence",
			Handler:    _SentenceGen_GenerateSentence_Handler,
		},
		{
			MethodName: "Translate",
			Handler:    _SentenceGen_Translate_Handler,
		},
		{
			MethodName: "GenerateDefinition",
			Handler:    _SentenceGen_GenerateDefinition_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/sentence-gen.proto",
}
